#!/usr/bin/env python3

# WEEK THREE PORTFOLIO

# 1

# blank name input
if __name__ == '__main__':
    name = input("Hello, what is your name?  ")
if not name:
    print("Hello stranger!")
else:
    print("Hello", name, ", nice to meet you!")
print()

# 2/3/4/5

# enter password
while True:
    password = input("Enter password:  ")
    confirm_password = input("Confirm password:  ")
# list of common password
    bad_passwords = ["password", "letmein", "sesame", "hello", "justinbieber"]

# password length
    if len(password) < 8:
     print("Password too short, please make between 8-12 characters.")
    elif len(password) > 12:
     print("Password too long, please enter between 8-12 characters.")
    else:
        if password == confirm_password:
            if password not in bad_passwords:
                print("Password set.")
            else:
                print("This is a common password, please choose a different one.")
        else:
            print("Passwords do not match, try entering again.")

# 6

for x in range(13):
    result = x * 7
    print(x, "x 7", result)